# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "puppet-qatools"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["attachmentgenie"]
  s.date = "2012-01-23"
  s.description = "Meta Package for the Puppet Quality Assurance Toolchain"
  s.email = "bram@attachmentgenie.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/puppet-qatools.rb",
    "puppet-qatools.gemspec",
    "test/helper.rb",
    "test/test_puppet-qatools.rb"
  ]
  s.homepage = "http://github.com/attachmentgenie/puppet-qatools"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Meta Package for the Puppet Quality Assurance Toolchain"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.7.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<puppet-profiler>, [">= 0"])
      s.add_runtime_dependency(%q<cucumber-puppet>, [">= 0"])
      s.add_runtime_dependency(%q<puppet-module>, [">= 0"])
      s.add_runtime_dependency(%q<puppet-lint>, [">= 0"])
      s.add_runtime_dependency(%q<rspec-puppet>, [">= 0"])
      s.add_runtime_dependency(%q<Finger-Puppet>, [">= 0"])
      s.add_runtime_dependency(%q<puppet-testing>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.7.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<puppet-profiler>, [">= 0"])
      s.add_dependency(%q<cucumber-puppet>, [">= 0"])
      s.add_dependency(%q<puppet-module>, [">= 0"])
      s.add_dependency(%q<puppet-lint>, [">= 0"])
      s.add_dependency(%q<rspec-puppet>, [">= 0"])
      s.add_dependency(%q<Finger-Puppet>, [">= 0"])
      s.add_dependency(%q<puppet-testing>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.7.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<puppet-profiler>, [">= 0"])
    s.add_dependency(%q<cucumber-puppet>, [">= 0"])
    s.add_dependency(%q<puppet-module>, [">= 0"])
    s.add_dependency(%q<puppet-lint>, [">= 0"])
    s.add_dependency(%q<rspec-puppet>, [">= 0"])
    s.add_dependency(%q<Finger-Puppet>, [">= 0"])
    s.add_dependency(%q<puppet-testing>, [">= 0"])
  end
end

